# Generated by Django 5.0.3 on 2024-03-08 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DM', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='gold',
            field=models.IntegerField(default=0),
        ),
    ]
