# Generated by Django 5.0.3 on 2024-03-09 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DM', '0002_inventory_gold'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('text', models.TextField()),
            ],
        ),
    ]
