# Generated by Django 5.0.3 on 2024-03-15 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DM', '0003_changelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='hp',
            field=models.IntegerField(default=100),
        ),
    ]
